#!/bin/sh
# Run all available spiders.

set -e

# Usage
[ "$#" -ne 1 ] && echo "usage: $0 ATOM_OUTPUT_PATH" && exit 1

cd "$(dirname "$0")"
. ./venv/bin/activate
scrapy list | xargs -n 1 -P 0 scrapy crawl --set ATOM_OUTPUT_PATH="$1"
python ./generate-index "$1"
