#!/bin/sh
# Update version information.

set -e
set -u

# Version information.
FEEDS_VERSION="2017.08.14"
FEEDS_YEAR="$(date +%Y)"

update_docs() {
  local conffile="docs/conf.py"

  # Version and year
  sed -i -E "/^version = /s/'.*'/'$FEEDS_VERSION'/" "$conffile"
  sed -i -E "/^release = /s/'.*'/'$FEEDS_VERSION'/" "$conffile"
  sed -i -E "/^copyright = /s/[0-9]{4}/$FEEDS_YEAR/" "$conffile"
}

update_setup() {
  local conffile="setup.py"

  sed -i -E "/version=/s/'.*'/'$FEEDS_VERSION'/" "$conffile"
}

update_init() {
  local conffile="feeds/__init__.py"

  sed -i -E "/^__version__ = /s/'.*'/'$FEEDS_VERSION'/" "$conffile"
}

main() {
  update_docs
  update_setup
  update_init
}

main
