---

name: PyFeeds CI
on: [push]

# Run tests against each supported version while docs and check-style are only
# considered on the latest supported version.
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.8"
            toxenv: py38
          - version: "3.9"
            toxenv: py39
          - version: "3.10"
            toxenv: py310
          - version: "3.11"
            toxenv: py311,docs,check-style

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python.version }} and tox ${{ matrix.python.toxenv }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install Tox
        run: |
          pip install tox

      - name: Run Tox
        run: |
          tox -e ${{ matrix.python.toxenv }}
